# Generated by Django 4.1.5 on 2023-01-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='order_date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='payement',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payement_id',
            new_name='razorpay_payment_id',
        ),
    ]
