# Generated by Django 4.1.5 on 2023-01-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Casablanca', 'Casablanca'), ('Salé', 'Salé'), ('Tanger', 'Tanger'), ('Fès', 'Fès'), ('Marrakech', 'Marrakech'), ('Safi', 'Safi'), ('Meknès', 'Meknès'), ('Oujda', 'Oujda'), ('Rabat', 'Rabat'), ('Témara', 'Témara'), ('Agadir', 'Agadir'), ('Kénitra', 'Kénitra'), ('Tétouan', 'Tétouan'), ('Laayoune', 'Laayoune'), ('Mohammédia', 'Mohammédia'), ('El Jadida', 'El Jadida'), ('Khouribga', 'Khouribga'), ('Béni Mellal', 'Béni Mellal'), ('Khémisset', 'Khémisset'), ('Nador', 'Nador'), ('Taza', 'Taza'), ('Berkane', 'Berkane')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CT', 'Chats'), ('CN', 'Chiens'), ('OS', 'Oiseaux'), ('PS', 'Poissons'), ('RP', 'Reptiles'), ('RG', 'Rongeurs')], max_length=2),
        ),
    ]
